In [2]:
# Master
import pandas as pd

In [4]:
teams = pd.read_pickle("../../data/teams.csv")

In [5]:
teams.head()

,id,name,link,abbreviation,teamName,locationName,firstYearOfPlay,shortName,officialSiteUrl,franchiseId,...,division_nameShort,division_link,division_abbreviation,conference_id,conference_name,conference_link,franchise_franchiseId,franchise_teamName,franchise_link,venue_id
0,1,New Jersey Devils,/api/v1/teams/1,NJD,Devils,New Jersey,1982,New Jersey,http://www.newjerseydevils.com/,23,...,Metro,/api/v1/divisions/18,M,6,Eastern,/api/v1/conferences/6,23,Devils,/api/v1/franchises/23,NaN
1,2,New York Islanders,/api/v1/teams/2,NYI,Islanders,New York,1972,NY Islanders,http://www.newyorkislanders.com/,22,...,Metro,/api/v1/divisions/18,M,6,Eastern,/api/v1/conferences/6,22,Islanders,/api/v1/franchises/22,5026.0
2,3,New York Rangers,/api/v1/teams/3,NYR,Rangers,New York,1926,NY Rangers,http://www.newyorkrangers.com/,10,...,Metro,/api/v1/divisions/18,M,6,Eastern,/api/v1/conferences/6,10,Rangers,/api/v1/franchises/10,5054.0
3,4,Philadelphia Flyers,/api/v1/teams/4,PHI,Flyers,Philadelphia,1967,Philadelphia,http://www.philadelphiaflyers.com/,16,...,Metro,/api/v1/divisions/18,M,6,Eastern,/api/v1/conferences/6,16,Flyers,/api/v1/franchises/16,5096.0
4,5,Pittsburgh Penguins,/api/v1/teams/5,PIT,Penguins,Pittsburgh,1967,Pittsburgh,http://pittsburghpenguins.com/,17,...,Metro,/api/v1/divisions/18,M,6,Eastern,/api/v1/conferences/6,17,Penguins,/api/v1/franchises/17,5034.0